version: "3"
services:
  mongodb:
    image: mongo:3.0.2
    ports:
      - "27017:27017"
  redis:
    image: "redis"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  web:
    build: ./web
    ports:
      - "5050:5050"
    volumes:
      - ./web:/code
    links:
    - mongodb
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb
    restart: on-failure